// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated from html_names.json
// Generated by generate_names.dart

import 'dom.dart';
import 'namespaces.dart';

const String aTag = 'a';
const QName aQName = QName(name: 'a', namespace: htmlNamespace);

const String abbrTag = 'abbr';
const QName abbrQName = QName(name: 'abbr', namespace: htmlNamespace);

const String acronymTag = 'acronym';
const QName acronymQName = QName(name: 'acronym', namespace: htmlNamespace);

const String addressTag = 'address';
const QName addressQName = QName(name: 'address', namespace: htmlNamespace);

const String appletTag = 'applet';
const QName appletQName = QName(name: 'applet', namespace: htmlNamespace);

const String areaTag = 'area';
const QName areaQName = QName(name: 'area', namespace: htmlNamespace);

const String articleTag = 'article';
const QName articleQName = QName(name: 'article', namespace: htmlNamespace);

const String asideTag = 'aside';
const QName asideQName = QName(name: 'aside', namespace: htmlNamespace);

const String attachmentTag = 'attachment';
const QName attachmentQName =
    QName(name: 'attachment', namespace: htmlNamespace);

const String audioTag = 'audio';
const QName audioQName = QName(name: 'audio', namespace: htmlNamespace);

const String bTag = 'b';
const QName bQName = QName(name: 'b', namespace: htmlNamespace);

const String baseTag = 'base';
const QName baseQName = QName(name: 'base', namespace: htmlNamespace);

const String basefontTag = 'basefont';
const QName basefontQName = QName(name: 'basefont', namespace: htmlNamespace);

const String bdiTag = 'bdi';
const QName bdiQName = QName(name: 'bdi', namespace: htmlNamespace);

const String bdoTag = 'bdo';
const QName bdoQName = QName(name: 'bdo', namespace: htmlNamespace);

const String bgsoundTag = 'bgsound';
const QName bgsoundQName = QName(name: 'bgsound', namespace: htmlNamespace);

const String bigTag = 'big';
const QName bigQName = QName(name: 'big', namespace: htmlNamespace);

const String blockquoteTag = 'blockquote';
const QName blockquoteQName =
    QName(name: 'blockquote', namespace: htmlNamespace);

const String bodyTag = 'body';
const QName bodyQName = QName(name: 'body', namespace: htmlNamespace);

const String brTag = 'br';
const QName brQName = QName(name: 'br', namespace: htmlNamespace);

const String buttonTag = 'button';
const QName buttonQName = QName(name: 'button', namespace: htmlNamespace);

const String canvasTag = 'canvas';
const QName canvasQName = QName(name: 'canvas', namespace: htmlNamespace);

const String captionTag = 'caption';
const QName captionQName = QName(name: 'caption', namespace: htmlNamespace);

const String centerTag = 'center';
const QName centerQName = QName(name: 'center', namespace: htmlNamespace);

const String citeTag = 'cite';
const QName citeQName = QName(name: 'cite', namespace: htmlNamespace);

const String codeTag = 'code';
const QName codeQName = QName(name: 'code', namespace: htmlNamespace);

const String colTag = 'col';
const QName colQName = QName(name: 'col', namespace: htmlNamespace);

const String colgroupTag = 'colgroup';
const QName colgroupQName = QName(name: 'colgroup', namespace: htmlNamespace);

const String commandTag = 'command';
const QName commandQName = QName(name: 'command', namespace: htmlNamespace);

const String dataTag = 'data';
const QName dataQName = QName(name: 'data', namespace: htmlNamespace);

const String datalistTag = 'datalist';
const QName datalistQName = QName(name: 'datalist', namespace: htmlNamespace);

const String ddTag = 'dd';
const QName ddQName = QName(name: 'dd', namespace: htmlNamespace);

const String delTag = 'del';
const QName delQName = QName(name: 'del', namespace: htmlNamespace);

const String detailsTag = 'details';
const QName detailsQName = QName(name: 'details', namespace: htmlNamespace);

const String dfnTag = 'dfn';
const QName dfnQName = QName(name: 'dfn', namespace: htmlNamespace);

const String dialogTag = 'dialog';
const QName dialogQName = QName(name: 'dialog', namespace: htmlNamespace);

const String dirTag = 'dir';
const QName dirQName = QName(name: 'dir', namespace: htmlNamespace);

const String divTag = 'div';
const QName divQName = QName(name: 'div', namespace: htmlNamespace);

const String dlTag = 'dl';
const QName dlQName = QName(name: 'dl', namespace: htmlNamespace);

const String dtTag = 'dt';
const QName dtQName = QName(name: 'dt', namespace: htmlNamespace);

const String emTag = 'em';
const QName emQName = QName(name: 'em', namespace: htmlNamespace);

const String embedTag = 'embed';
const QName embedQName = QName(name: 'embed', namespace: htmlNamespace);

const String fieldsetTag = 'fieldset';
const QName fieldsetQName = QName(name: 'fieldset', namespace: htmlNamespace);

const String figcaptionTag = 'figcaption';
const QName figcaptionQName =
    QName(name: 'figcaption', namespace: htmlNamespace);

const String figureTag = 'figure';
const QName figureQName = QName(name: 'figure', namespace: htmlNamespace);

const String fontTag = 'font';
const QName fontQName = QName(name: 'font', namespace: htmlNamespace);

const String footerTag = 'footer';
const QName footerQName = QName(name: 'footer', namespace: htmlNamespace);

const String formTag = 'form';
const QName formQName = QName(name: 'form', namespace: htmlNamespace);

const String frameTag = 'frame';
const QName frameQName = QName(name: 'frame', namespace: htmlNamespace);

const String framesetTag = 'frameset';
const QName framesetQName = QName(name: 'frameset', namespace: htmlNamespace);

const String h1Tag = 'h1';
const QName h1QName = QName(name: 'h1', namespace: htmlNamespace);

const String h2Tag = 'h2';
const QName h2QName = QName(name: 'h2', namespace: htmlNamespace);

const String h3Tag = 'h3';
const QName h3QName = QName(name: 'h3', namespace: htmlNamespace);

const String h4Tag = 'h4';
const QName h4QName = QName(name: 'h4', namespace: htmlNamespace);

const String h5Tag = 'h5';
const QName h5QName = QName(name: 'h5', namespace: htmlNamespace);

const String h6Tag = 'h6';
const QName h6QName = QName(name: 'h6', namespace: htmlNamespace);

const String headTag = 'head';
const QName headQName = QName(name: 'head', namespace: htmlNamespace);

const String headerTag = 'header';
const QName headerQName = QName(name: 'header', namespace: htmlNamespace);

const String hgroupTag = 'hgroup';
const QName hgroupQName = QName(name: 'hgroup', namespace: htmlNamespace);

const String hrTag = 'hr';
const QName hrQName = QName(name: 'hr', namespace: htmlNamespace);

const String htmlTag = 'html';
const QName htmlQName = QName(name: 'html', namespace: htmlNamespace);

const String iTag = 'i';
const QName iQName = QName(name: 'i', namespace: htmlNamespace);

const String iframeTag = 'iframe';
const QName iframeQName = QName(name: 'iframe', namespace: htmlNamespace);

const String imageTag = 'image';
const QName imageQName = QName(name: 'image', namespace: htmlNamespace);

const String imgTag = 'img';
const QName imgQName = QName(name: 'img', namespace: htmlNamespace);

const String inputTag = 'input';
const QName inputQName = QName(name: 'input', namespace: htmlNamespace);

const String insTag = 'ins';
const QName insQName = QName(name: 'ins', namespace: htmlNamespace);

const String kbdTag = 'kbd';
const QName kbdQName = QName(name: 'kbd', namespace: htmlNamespace);

const String keygenTag = 'keygen';
const QName keygenQName = QName(name: 'keygen', namespace: htmlNamespace);

const String labelTag = 'label';
const QName labelQName = QName(name: 'label', namespace: htmlNamespace);

const String layerTag = 'layer';
const QName layerQName = QName(name: 'layer', namespace: htmlNamespace);

const String legendTag = 'legend';
const QName legendQName = QName(name: 'legend', namespace: htmlNamespace);

const String liTag = 'li';
const QName liQName = QName(name: 'li', namespace: htmlNamespace);

const String linkTag = 'link';
const QName linkQName = QName(name: 'link', namespace: htmlNamespace);

const String listingTag = 'listing';
const QName listingQName = QName(name: 'listing', namespace: htmlNamespace);

const String mainTag = 'main';
const QName mainQName = QName(name: 'main', namespace: htmlNamespace);

const String mapTag = 'map';
const QName mapQName = QName(name: 'map', namespace: htmlNamespace);

const String markTag = 'mark';
const QName markQName = QName(name: 'mark', namespace: htmlNamespace);

const String marqueeTag = 'marquee';
const QName marqueeQName = QName(name: 'marquee', namespace: htmlNamespace);

const String menuTag = 'menu';
const QName menuQName = QName(name: 'menu', namespace: htmlNamespace);

const String menuitemTag = 'menuitem';
const QName menuitemQName = QName(name: 'menuitem', namespace: htmlNamespace);

const String metaTag = 'meta';
const QName metaQName = QName(name: 'meta', namespace: htmlNamespace);

const String meterTag = 'meter';
const QName meterQName = QName(name: 'meter', namespace: htmlNamespace);

const String modelTag = 'model';
const QName modelQName = QName(name: 'model', namespace: htmlNamespace);

const String navTag = 'nav';
const QName navQName = QName(name: 'nav', namespace: htmlNamespace);

const String nobrTag = 'nobr';
const QName nobrQName = QName(name: 'nobr', namespace: htmlNamespace);

const String noembedTag = 'noembed';
const QName noembedQName = QName(name: 'noembed', namespace: htmlNamespace);

const String noframesTag = 'noframes';
const QName noframesQName = QName(name: 'noframes', namespace: htmlNamespace);

const String nolayerTag = 'nolayer';
const QName nolayerQName = QName(name: 'nolayer', namespace: htmlNamespace);

const String objectTag = 'object';
const QName objectQName = QName(name: 'object', namespace: htmlNamespace);

const String olTag = 'ol';
const QName olQName = QName(name: 'ol', namespace: htmlNamespace);

const String optgroupTag = 'optgroup';
const QName optgroupQName = QName(name: 'optgroup', namespace: htmlNamespace);

const String optionTag = 'option';
const QName optionQName = QName(name: 'option', namespace: htmlNamespace);

const String outputTag = 'output';
const QName outputQName = QName(name: 'output', namespace: htmlNamespace);

const String pTag = 'p';
const QName pQName = QName(name: 'p', namespace: htmlNamespace);

const String paramTag = 'param';
const QName paramQName = QName(name: 'param', namespace: htmlNamespace);

const String pictureTag = 'picture';
const QName pictureQName = QName(name: 'picture', namespace: htmlNamespace);

const String plaintextTag = 'plaintext';
const QName plaintextQName = QName(name: 'plaintext', namespace: htmlNamespace);

const String preTag = 'pre';
const QName preQName = QName(name: 'pre', namespace: htmlNamespace);

const String progressTag = 'progress';
const QName progressQName = QName(name: 'progress', namespace: htmlNamespace);

const String qTag = 'q';
const QName qQName = QName(name: 'q', namespace: htmlNamespace);

const String rbTag = 'rb';
const QName rbQName = QName(name: 'rb', namespace: htmlNamespace);

const String rpTag = 'rp';
const QName rpQName = QName(name: 'rp', namespace: htmlNamespace);

const String rtTag = 'rt';
const QName rtQName = QName(name: 'rt', namespace: htmlNamespace);

const String rtcTag = 'rtc';
const QName rtcQName = QName(name: 'rtc', namespace: htmlNamespace);

const String rubyTag = 'ruby';
const QName rubyQName = QName(name: 'ruby', namespace: htmlNamespace);

const String sTag = 's';
const QName sQName = QName(name: 's', namespace: htmlNamespace);

const String sampTag = 'samp';
const QName sampQName = QName(name: 'samp', namespace: htmlNamespace);

const String scriptTag = 'script';
const QName scriptQName = QName(name: 'script', namespace: htmlNamespace);

const String sectionTag = 'section';
const QName sectionQName = QName(name: 'section', namespace: htmlNamespace);

const String selectTag = 'select';
const QName selectQName = QName(name: 'select', namespace: htmlNamespace);

const String slotTag = 'slot';
const QName slotQName = QName(name: 'slot', namespace: htmlNamespace);

const String smallTag = 'small';
const QName smallQName = QName(name: 'small', namespace: htmlNamespace);

const String sourceTag = 'source';
const QName sourceQName = QName(name: 'source', namespace: htmlNamespace);

const String spanTag = 'span';
const QName spanQName = QName(name: 'span', namespace: htmlNamespace);

const String strikeTag = 'strike';
const QName strikeQName = QName(name: 'strike', namespace: htmlNamespace);

const String strongTag = 'strong';
const QName strongQName = QName(name: 'strong', namespace: htmlNamespace);

const String styleTag = 'style';
const QName styleQName = QName(name: 'style', namespace: htmlNamespace);

const String subTag = 'sub';
const QName subQName = QName(name: 'sub', namespace: htmlNamespace);

const String summaryTag = 'summary';
const QName summaryQName = QName(name: 'summary', namespace: htmlNamespace);

const String supTag = 'sup';
const QName supQName = QName(name: 'sup', namespace: htmlNamespace);

const String tableTag = 'table';
const QName tableQName = QName(name: 'table', namespace: htmlNamespace);

const String tbodyTag = 'tbody';
const QName tbodyQName = QName(name: 'tbody', namespace: htmlNamespace);

const String tdTag = 'td';
const QName tdQName = QName(name: 'td', namespace: htmlNamespace);

const String templateTag = 'template';
const QName templateQName = QName(name: 'template', namespace: htmlNamespace);

const String textareaTag = 'textarea';
const QName textareaQName = QName(name: 'textarea', namespace: htmlNamespace);

const String tfootTag = 'tfoot';
const QName tfootQName = QName(name: 'tfoot', namespace: htmlNamespace);

const String thTag = 'th';
const QName thQName = QName(name: 'th', namespace: htmlNamespace);

const String theadTag = 'thead';
const QName theadQName = QName(name: 'thead', namespace: htmlNamespace);

const String timeTag = 'time';
const QName timeQName = QName(name: 'time', namespace: htmlNamespace);

const String titleTag = 'title';
const QName titleQName = QName(name: 'title', namespace: htmlNamespace);

const String trTag = 'tr';
const QName trQName = QName(name: 'tr', namespace: htmlNamespace);

const String trackTag = 'track';
const QName trackQName = QName(name: 'track', namespace: htmlNamespace);

const String ttTag = 'tt';
const QName ttQName = QName(name: 'tt', namespace: htmlNamespace);

const String uTag = 'u';
const QName uQName = QName(name: 'u', namespace: htmlNamespace);

const String ulTag = 'ul';
const QName ulQName = QName(name: 'ul', namespace: htmlNamespace);

const String varTag = 'var';
const QName varQName = QName(name: 'var', namespace: htmlNamespace);

const String videoTag = 'video';
const QName videoQName = QName(name: 'video', namespace: htmlNamespace);

const String wbrTag = 'wbr';
const QName wbrQName = QName(name: 'wbr', namespace: htmlNamespace);

const String xmpTag = 'xmp';
const QName xmpQName = QName(name: 'xmp', namespace: htmlNamespace);

const String noscriptTag = 'noscript';
const QName noscriptQName = QName(name: 'noscript', namespace: htmlNamespace);
