// FIXME: This should be autogenerated

import 'package:html6/src/dom.dart';

const String htmlTag = 'html';
const QName htmlQName = QName.html('html');

const String headTag = 'head';
const QName headQName = QName.html('head');

const String scriptTag = 'script';
const QName scriptQName = QName.html('script');

const String bodyTag = 'body';
const QName bodyQName = QName.html('body');

const String brTag = 'br';
const QName brQName = QName.html('br');
